#lang racket

(define (make-dual n d) (cons n d))
(define (val x)  (car x))
(define (dval x) (cdr x))
(define (make-variable x) (make-dual x 1))

(define (add-dual u v)
    (make-dual (+ (val u)  (val v))
         (+ (dval u) (dval v))))

(define (sub-dual u v)
    (make-dual (- (val u)  (val v))
         (- (dval u) (dval v))))
(define (mult-dual u v)
    (make-dual (* (val u)  (val v))
         (+ (* (dval u) (dval v)) (* (val u) (dval v)))))
(define (div-dual u v)
  (if (= (val v) 0)
      (error "Cannot use one of the values, cannot divide by 0")
      (make-dual (/ (val u) (val v))
         (/ (- (* (dval u) (val v)) (* (val u) (dval v))) (* (val v) (val v))))))
(define (sin-dual u)
    (make-dual (sin(val u))
         (* (dval u) (cos(val u)))))
(define (cos-dual u)
    (make-dual (cos(val u))
         (* -1 (dval u) (sin(val u)))))
(define (exp-dual u) ;; exp -> ln
    (make-dual (exp (val u))
         (* (dval u) (exp (val u)))))
(define (log-dual u)
    (make-dual (log (val u))
         (/ (dval u) (val u))))
(define (pow-dual u k)
    (make-dual (expt (val u) (val k))
         (* (val k) (expt (val u) (- (val k) 1)) (dval u))))
(define (abs-dual u)
    (make-dual (abs (val u))
         (* (dval u) (sign (val u)))))

(define (sign i)
  (if (< i 0)
      -1
      (if (= i 0)
          0
          1))
  )

(define x (make-variable 2))
(add-dual x x)
(sub-dual x x)
(mult-dual x x)
(div-dual x x)
(sin-dual x)
(cos-dual x)
(exp-dual x)
(log-dual x)
(pow-dual x x)
(abs-dual x)


(define (make-constant a)
       (make-dual a 0))

(div-dual (make-constant 1)
          (cos-dual (pow-dual (sin-dual x) (make-constant 2))))
(define (sum? val) (equal? "+"))

(define (deval expr symbol value)
     (cond ((number? expr) 0)
           ((variable? expr)
            (if (same-variable? expr symbol) 1 0))
           ((sum? expr)
            (add-dual (make-constant (car expr)) (make-constant (cadr expr)))) ;;USE CAR CDR
;           ((sub? expr)
;            (sub-dual (make-constant (car expr)) (make-variable (cadr expr))))
;           ((product? expr)
;            (mult-dual (make-constant (car expr)) (make-variable (cadr expr))))
;           ((difference? expr)
;            (div-dual (make-constant (car expr)) (make-variable (cadr expr))))
;           ((sin? expr)
;            (sin-dual (make-constant (car expr))))
;           ((cos? expr)
;            (cos-dual (make-constant (car expr))))
;           ((exp? expr)
;            (exp-dual (make-constant (car expr))))
;           ((log? expr)
;            (log-dual (make-constant (car expr))))
;           ((pow? expr)
;            (pow-dual (make-constant (car expr)) (make-constant (cadr expr))))
;           ((abs? expr)
;            (abs-dual (make-constant (car expr))))
           (else
            (error "Unknown expression type:" expr))))

(deval '(+ x 2) 'x 2)

